<?php

use Illuminate\Support\Facades\Route;
use App\Mail\sendAutoGeneratedPassword;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use App\Http\Controllers\UserController;
use App\Jobs\SendEmail;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/test', function () {
    dispatch(new SendEmail("123456789", "test@test.com"));
    // $user = DB::select('select * from users where email = :email', ['email' => $email]);

    // Mail::to($email)->send(new \App\Mail\sendAutoGeneratedPassword($user[0]->name, $password));

    // return "Email sent";
});

Route::post('/send-mail/{password}/{email}', function ($password, $email) {
    dispatch(new SendEmail($password, $email));
    // $user = DB::select('select * from users where email = :email', ['email' => $email]);

    // Mail::to($email)->send(new \App\Mail\sendAutoGeneratedPassword($user[0]->name, $password));

    // return "Email sent";
});


Route::get('/login', function () {
    return view('welcome');
});

Route::get('/', function () {
    Log::debug("hi");
    return view('welcome');
});

Route::get('/home', function () {
    return view('welcome');
});

Route::get('/register', function () {
    return view('welcome');
});

Route::get('/favorites', function () {
    return view('welcome');
});

Auth::routes();
